version: 2.1
parameters:
  tag_regex:
    type: string
    default: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
jobs:
  lint:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_2.13.11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
      - run: sbt ++2.13.11! check
      - save_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - "~/.cache/coursier/v1"
  test213_jdk17:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_2.13.11
      - image: rabbitmq:latest
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
      - run: sbt ++2.13.11! test
      - store_test_results:
          path: target/test-reports 
  test330_jdk17:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_3.3.0
      - image: rabbitmq:latest
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
      - run: sbt ++3.3.0! test
  test212_jdk17:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_2.12.18
      - image: rabbitmq:latest
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
      - run: sbt ++2.12.18! test
  release:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_2.13.11
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
      - run: apt install -y gnupg
      - run: export GPG_TTY=$(tty)
      - run: echo $PGP_SECRET | base64 --decode | gpg --batch --import
      - run: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
      - run: sbt ci-release
workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - test213_jdk17:
          requires:
            - lint
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - test212_jdk17:
          requires:
            - lint
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - test330_jdk17:
          requires:
            - lint
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - release:
          requires:
            - test213_jdk17
            - test212_jdk17
            - test330_jdk17
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/
